export const BYTES_PER_MB = 1024 * 1024

export const MAX_UPLOAD_SIZE_MB = 50

export const ARCHIVE_TOTAL_MB = 1024


export const SIMULATED_FLOWS_ENABLED = import.meta.env.DEV
export const SIMULATED_UPLOAD_DURATION_MS = SIMULATED_FLOWS_ENABLED ? 5000 : 0
export const SIMULATED_STAMPING_DURATION_MS = SIMULATED_FLOWS_ENABLED ? 5000 : 0
export const STAMPING_TICK_INTERVAL_MS = 140
export const STAMPING_RESET_DELAY_MS = 450

export const PREVIEW_TICK_INCREMENT = 8
export const PREVIEW_TICK_INTERVAL_MS = 180
export const SIMULATED_PROGRESS_TICK_MS = 100

export const HTTP_DEFAULT_TIMEOUT_MS = 10_000
export const UPLOAD_TIMEOUT_MS = 5 * 60 * 1000

export const RECENT_DOCUMENTS_VISIBLE_LIMIT = 5
export const LATEST_ACTIVITIES_LIMIT = 4

export const TOAST_DEFAULT_DURATION_MS = 4000

export const PASSWORD_MIN_LENGTH = 8
